
root: true
parser: "@typescript-eslint/parser"
plugins:
    - "@typescript-eslint"

extends:
    - "eslint:recommended"
    - "plugin:@typescript-eslint/recommended"
    - "plugin:react/recommended"

env: 
    browser: true
    node: true

settings:
    react:
        createClass: "createReactClass"
        pragma: "React" 
        version: "detect"

rules:
    max-len:
        - 2
        - code: 160
    no-cond-assign: 2
    no-multiple-empty-lines:
        - 1
        - max: 3
    semi:
        - 2
        - "always"
    no-console: 1
    no-magic-numbers: 2
    interface-name: 0
    one-line: 0
    member-ordering: 0
    object-literal-sort-keys: 0
