
root: true
parser: "@typescript-eslint/parser"
plugins:
    - "@typescript-eslint"

extends:
    - "eslint:recommended"
    - "plugin:@typescript-eslint/recommended"
    - "plugin:react/recommended"

env: 
    browser: true
    node: true

settings:
    react:
        createClass: "createReactClass"
        pragma: "React" 
        version: "detect"

rules:
    max-len:
        - 2
        - code: 160
    no-cond-assign: 2
    no-multiple-empty-lines:
        - 1
        - max: 3
    semi:
        - 2
        - "always"
    no-console: 1
    interface-name: 0
    one-line: 0
    member-ordering: 0
    object-literal-sort-keys: 0

    react/jsx-curly-brace-presence:
        - 2
        - props: always
          children: always
    react/jsx-key: 1

    "@typescript-eslint/explicit-member-accessibility": 2
    "@typescript-eslint/explicit-function-return-type":
        - 2
        - allowExpressions: true
    "@typescript-eslint/no-inferrable-types": 0
    "@typescript-eslint/no-magic-numbers":
        - 2
        - ignoreReadonlyClassProperties: true
          ignoreEnums: true
    "@typescript-eslint/array-type":
        - 2
        - array: true
