extends: stylelint-config-standard
rules:
    indentation: 4
    max-empty-lines: 2
    declaration-empty-line-before: null
    no-descending-specificity: null
    at-rule-no-unknown:
        - true
        - ignoreAtRules:
            - mixin
            - include
