
services:

  recipe-book-api:
    image: web-api
    build: ./services/web-api
    depends_on:
      - recipe-book-db
    ports:
      - 8080:8080
    working_dir: /web-api
    environment:
      RB__listen_addr: 0.0.0.0:8080
      RB__database_url: postgres://postgres:password@recipe-book-db

  recipe-book-app:
    image: web-app
    build:
      context: ./services/web-app
      args:
        - RB__API_ADDR=recipe-book-api:8080
    depends_on:
      - recipe-book-api
    ports:
      - 3000:3000
    working_dir: /app
    environment:
      RB__API_ADDR: recipe-book-api:8080
      NODE_ENV: production     # options: production, development
      PORT: 3000
      LOG_LEVEL: DEBUG

  recipe-book-docs:
    image: docs-app
    build:
      context: ./services/docs-app
    ports:
      - 3001:3000
    working_dir: /app
    environment:
      NODE_ENV: production     # options: production, development
      PORT: 3000
      LOG_LEVEL: DEBUG

  recipe-book-scraper:
    image: recipe-scraper
    build: ./services/recipe-scraper
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    depends_on:
      - recipe-book-db
    ports:
      - 8000:8000
    working_dir: /app

  recipe-book-keycloak:
    image: quay.io/keycloak/keycloak:20.0.1
    command: start-dev
    ports:
      - 3002:8080
    depends_on:
      - recipe-book-db
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://recipe-book-db/keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: password
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin

  recipe-book-db:
    image: postgres:14
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - 5432:5432
    environment:
      PGUSER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - postgres-db:/var/lib/postgresql/data
      - ./keycloak_db_init.sql:/docker-entrypoint-initdb.d/keycloak_db_init.sql

  # recipe-book-db-admin:
  #   image: dpage/pgadmin4:latest
  #   depends_on:
  #     - recipe-book-db
  #   ports:
  #     - 5050:5050
  #   environment:
  #     - PGADMIN_DEFAULT_EMAIL=admin@greams.com
  #     - PGADMIN_DEFAULT_PASSWORD=password
  #     - PGADMIN_LISTEN_PORT=5050
  #   volumes:
  #     - postgres-admin:/var/lib/pgadmin
  #   links:
  #     - recipe-book-db:pgsql-server

volumes:
  postgres-db:
  postgres-admin:
