version: "3.8"

services:

  app:
    build: .
    command: npm run dev:watch
    ports:
      - 8080:8080
    working_dir: /app
    volumes:
      - ./src:/app/src
    environment:
      # options: production, development
      NODE_ENV: development
      PORT: 8080
      LOG_LEVEL: DEBUG
      MONGODB_URL: mongodb:27017

  mongodb:
    image: mongo:4.4
    volumes:
      - $HOME/dev/personal/recipe-book/recipe-book-app/mongodb:/data/db
    ports:
      - 27017:27017
    # environment: 
    #   MONGO_INITDB_ROOT_USERNAME: root
    #   MONGO_INITDB_ROOT_PASSWORD: example

# volumes:
#   rba-mongodb-data:

