
services:

  rb-web-api:
    image: web-api
    build: ./services/web-api
    depends_on:
      rb-database:
        condition: service_healthy
    ports:
      - 8080:8080
    working_dir: /web-api
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/api/v1/health"]
      interval: 10s
      timeout: 5s
      retries: 30
      start_period: 60s
    environment:
      RB__listen_addr: 0.0.0.0:8080
      RB__database_url: postgres://postgres:password@rb-database

  rb-web-app:
    image: web-app
    build: ./services/web-app
    depends_on:
      - rb-web-api
    ports:
      - 3000:3000
    working_dir: /app
    environment:
      RB__API_ADDR: rb-web-api:8080
      NODE_ENV: production     # options: production, development
      PORT: 3000
      LOG_LEVEL: DEBUG

  rb-docs:
    image: docs-app
    build: ./services/docs-app
    ports:
      - 3001:3000
    working_dir: /app
    environment:
      NODE_ENV: production     # options: production, development
      PORT: 3000
      LOG_LEVEL: DEBUG

  rb-scraper:
    image: recipe-scraper
    build: ./services/recipe-scraper
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    depends_on:
      rb-database:
        condition: service_healthy
    ports:
      - 8000:8000
    working_dir: /app

  rb-auth-api:
    image: auth-api
    build: ./services/auth-api
    depends_on:
      - rb-keycloak
    ports:
      - 3003:8080
    working_dir: /auth-api
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/api/v1/health"]
      interval: 10s
      timeout: 5s
      retries: 30
      start_period: 60s
    environment:
      RB__listen_addr: 0.0.0.0:8080
      RB__keycloak__url: rb-keycloak:8080
      RB__keycloak__username: admin
      RB__keycloak__password: admin

  rb-keycloak:
    image: quay.io/keycloak/keycloak:20.0.1
    command: start-dev
    ports:
      - 3002:8080
    depends_on:
      rb-database:
        condition: service_healthy
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://rb-database/keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: password
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin

  rb-database:
    image: postgres:14
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - 5432:5432
    environment:
      PGUSER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - postgres-db:/var/lib/postgresql/data
      - ./keycloak_db_init.sql:/docker-entrypoint-initdb.d/keycloak_db_init.sql

  # rb-database-admin:
  #   image: dpage/pgadmin4:latest
  #   depends_on:
  #     - rb-database
  #   ports:
  #     - 5050:5050
  #   environment:
  #     - PGADMIN_DEFAULT_EMAIL=admin@greams.com
  #     - PGADMIN_DEFAULT_PASSWORD=password
  #     - PGADMIN_LISTEN_PORT=5050
  #   volumes:
  #     - postgres-admin:/var/lib/pgadmin
  #   links:
  #     - rb-database:pgsql-server

volumes:
  postgres-db:
  postgres-admin:
