version: "3.9"

services:

  recipe-book-api:
    image: web-api
    build: ./services/web-api
    depends_on:
      - recipe-book-db
    ports:
      - 8080:8080
    working_dir: /web-api
    environment:
      RB__listen_addr: 0.0.0.0:8080
      RB__database_url: postgres://postgres:password@recipe-book-db

  recipe-book-app:
    build: ./services/web-app
    depends_on:
      - recipe-book-api
    command: npm run dev
    ports:
      - 3000:3000
    working_dir: /app
    volumes:
      - $HOME/dev/personal/recipe-book/recipe-book-app/services/web-app:/app
    environment:
      RB__API_ADDR: recipe-book-api:8080
      NODE_ENV: development     # options: production, development
      PORT: 3000
      LOG_LEVEL: DEBUG

  recipe-book-db:
    image: postgres:14
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: password
    volumes:
      - $HOME/dev/personal/recipe-book/recipe-book-app/postgres:/var/lib/postgresql/data

  recipe-book-db-admin:
    image: dpage/pgadmin4:latest
    depends_on:
      - recipe-book-db
    ports:
      - 5050:5050
    environment:
      - PGADMIN_DEFAULT_EMAIL=user@domain.local
      - PGADMIN_DEFAULT_PASSWORD=password
      - PGADMIN_LISTEN_PORT=5050
    volumes:
      - $HOME/dev/personal/recipe-book/recipe-book-app/postgres-admin:/var/lib/pgadmin
    links:
      - recipe-book-db:pgsql-server
