
// GENERAL

export const CY_RECIPE_PATH = "/recipe";
export const CY_FOOD_PATH = "/food";
export const CY_USER_PATH = "/user";

export const CY_NEW_RECIPE_PATH = "/recipe/new";
export const CY_NEW_FOOD_PATH = "/food/new";

export const CY_RECIPE_API_PATH = "/api/v1/recipe";
export const CY_FOOD_API_PATH = "/api/v1/food";
export const CY_PRODUCT_API_PATH = "/api/v1/product";

// PAGE_TITLE

export const CY_PAGE_TITLE_BLOCK = "CY_PAGE_TITLE_BLOCK";
export const CY_PAGE_TITLE_NAME_TEXT = "CY_PAGE_TITLE_NAME_TEXT";
export const CY_PAGE_TITLE_BRAND_TEXT = "CY_PAGE_TITLE_BRAND_TEXT";
export const CY_PAGE_TITLE_SUBTITLE_TEXT = "CY_PAGE_TITLE_SUBTITLE_TEXT";
export const CY_PAGE_TITLE_DESCRIPTION_TEXT = "CY_PAGE_TITLE_DESCRIPTION_TEXT";

export const CY_PAGE_TITLE_NAME_INPUT = "CY_PAGE_TITLE_NAME_INPUT";
export const CY_PAGE_TITLE_BRAND_INPUT = "CY_PAGE_TITLE_BRAND_INPUT";
export const CY_PAGE_TITLE_SUBTITLE_INPUT = "CY_PAGE_TITLE_SUBTITLE_INPUT";
export const CY_PAGE_TITLE_DESCRIPTION_INPUT = "CY_PAGE_TITLE_DESCRIPTION_INPUT";

// CUSTOM_UNIT

export const CY_NEW_CUSTOM_UNIT_LINE = "CY_NEW_CUSTOM_UNIT_LINE";
export const CY_CUSTOM_UNIT_LINE = "CY_CUSTOM_UNIT_LINE";

export const CY_CUSTOM_UNIT_BUTTON = "CY_CUSTOM_UNIT_BUTTON";
export const CY_CUSTOM_UNIT_NAME = "CY_CUSTOM_UNIT_NAME";
export const CY_CUSTOM_UNIT_AMOUNT = "CY_CUSTOM_UNIT_AMOUNT";

export const CY_SELECT_INPUT = "CY_SELECT_INPUT";
export const CY_SELECT_INPUT_OPTION = "CY_SELECT_INPUT_OPTION";

// INGREDIENTS

export const CY_INGREDIENTS_BLOCK = "CY_INGREDIENTS_BLOCK";
export const CY_INGREDIENT = "CY_INGREDIENT";
export const CY_INGREDIENT_NUTRITION_FACT_AMOUNT = "CY_INGREDIENT_NUTRITION_FACT_AMOUNT";
export const CY_INGREDIENT_NUTRITION_FACT_TYPE = "CY_INGREDIENT_NUTRITION_FACT_TYPE";

export const CY_INGREDIENT_PRODUCT = "CY_INGREDIENT_PRODUCT";
export const CY_INGREDIENT_PRODUCT_NAME = "CY_INGREDIENT_PRODUCT_NAME";
export const CY_INGREDIENT_PRODUCT_REMOVE_BUTTON = "CY_INGREDIENT_PRODUCT_REMOVE_BUTTON";

// DIRECTIONS

export const CY_DIRECTION_LINE = "CY_DIRECTION_LINE";
export const CY_DIRECTION_LINE_CHECKBOX = "CY_DIRECTION_LINE_CHECKBOX";
export const CY_DIRECTION_LINE_REMOVE_BUTTON = "CY_DIRECTION_LINE_REMOVE_BUTTON";

export const CY_DIRECTION_INFO_LINE_NAME_TEXT = "CY_DIRECTION_INFO_LINE_NAME_TEXT";
export const CY_DIRECTION_INFO_LINE_NAME_INPUT = "CY_DIRECTION_INFO_LINE_NAME_INPUT";
export const CY_DIRECTION_INFO_LINE_TEMPERATURE_MEASURE = "CY_DIRECTION_INFO_LINE_TEMPERATURE_MEASURE";
export const CY_DIRECTION_INFO_LINE_DURATION_MEASURE = "CY_DIRECTION_INFO_LINE_DURATION_MEASURE";

export const CY_NEW_DIRECTION_LINE = "CY_NEW_DIRECTION_LINE";
export const CY_NEW_DIRECTION_LINE_CREATE_BUTTON = "CY_NEW_DIRECTION_LINE_CREATE_BUTTON";
export const CY_NEW_DIRECTION_INFO_LINE_TEMPERATURE_MEASURE = "CY_NEW_DIRECTION_INFO_LINE_TEMPERATURE_MEASURE";
export const CY_NEW_DIRECTION_INFO_LINE_DURATION_MEASURE = "CY_NEW_DIRECTION_INFO_LINE_DURATION_MEASURE";
export const CY_NEW_DIRECTION_INFO_LINE_TEMPERATURE_INPUT = "CY_NEW_DIRECTION_INFO_LINE_TEMPERATURE_INPUT";
export const CY_NEW_DIRECTION_INFO_LINE_DURATION_INPUT = "CY_NEW_DIRECTION_INFO_LINE_DURATION_INPUT";
export const CY_NEW_DIRECTION_INFO_LINE_STEP_INPUT = "CY_NEW_DIRECTION_INFO_LINE_STEP_INPUT";
export const CY_NEW_DIRECTION_INFO_LINE_NAME_INPUT = "CY_NEW_DIRECTION_INFO_LINE_NAME_INPUT";

export const CY_SUB_DIRECTION_LINE = "CY_SUB_DIRECTION_LINE";
export const CY_SUB_DIRECTION_LINE_NAME = "CY_SUB_DIRECTION_LINE_NAME";
export const CY_SUB_DIRECTION_LINE_CHECKBOX = "CY_SUB_DIRECTION_LINE_CHECKBOX";
export const CY_SUB_DIRECTION_LINE_REMOVE_BUTTON = "CY_SUB_DIRECTION_LINE_REMOVE_BUTTON";
export const CY_NEW_SUB_DIRECTION_LINE = "CY_NEW_SUB_DIRECTION_LINE";
export const CY_NEW_SUB_DIRECTION_LINE_CREATE_BUTTON = "CY_NEW_SUB_DIRECTION_LINE_CREATE_BUTTON";

// USER

export const CY_USER_MENU_ITEM = "CY_USER_MENU_ITEM";
export const CY_USER_RECIPE_CUSTOM_ITEM = "CY_USER_RECIPE_CUSTOM_ITEM";
export const CY_USER_RECIPE_FAVORITE_ITEM = "CY_USER_RECIPE_FAVORITE_ITEM";
export const CY_USER_FOOD_CUSTOM_ITEM = "CY_USER_FOOD_CUSTOM_ITEM";
export const CY_USER_FOOD_FAVORITE_ITEM = "CY_USER_FOOD_FAVORITE_ITEM";

// NAVBAR

export const CY_NAVBAR_USER_ITEM = "CY_NAVBAR_USER_ITEM";
export const CY_NAVBAR_LOGO_ITEM = "CY_NAVBAR_LOGO_ITEM";

// CREATE & UPDATE

export const CY_BUTTON = "CY_BUTTON";

// SEARCH

export const CY_SEARCH = "CY_SEARCH";
export const CY_SEARCH_INPUT = "CY_SEARCH_INPUT";
