
export const CY_RECIPE_PATH = "/recipe";
export const CY_FOOD_PATH = "/food";

export const CY_PAGE_TITLE_BLOCK = "CY_PAGE_TITLE_BLOCK";
export const CY_PAGE_TITLE_NAME_TEXT = "CY_PAGE_TITLE_NAME_TEXT";
export const CY_PAGE_TITLE_BRAND_TEXT = "CY_PAGE_TITLE_BRAND_TEXT";
export const CY_PAGE_TITLE_SUBTITLE_TEXT = "CY_PAGE_TITLE_SUBTITLE_TEXT";
export const CY_PAGE_TITLE_DESCRIPTION_TEXT = "CY_PAGE_TITLE_DESCRIPTION_TEXT";

export const CY_PAGE_TITLE_NAME_INPUT = "CY_PAGE_TITLE_NAME_INPUT";
export const CY_PAGE_TITLE_BRAND_INPUT = "CY_PAGE_TITLE_BRAND_INPUT";
export const CY_PAGE_TITLE_SUBTITLE_INPUT = "CY_PAGE_TITLE_SUBTITLE_INPUT";
export const CY_PAGE_TITLE_DESCRIPTION_INPUT = "CY_PAGE_TITLE_DESCRIPTION_INPUT";
export const CY_PAGE_TITLE_CONFIRM_BUTTON = "CY_PAGE_TITLE_CONFIRM_BUTTON";

export const CY_NEW_CUSTOM_UNIT_LINE = "CY_NEW_CUSTOM_UNIT_LINE";
export const CY_CUSTOM_UNIT_LINE = "CY_CUSTOM_UNIT_LINE";

export const CY_CUSTOM_UNIT_BUTTON = "CY_CUSTOM_UNIT_BUTTON";
export const CY_CUSTOM_UNIT_NAME = "CY_CUSTOM_UNIT_NAME";
export const CY_CUSTOM_UNIT_AMOUNT = "CY_CUSTOM_UNIT_AMOUNT";

export const CY_SELECT_INPUT = "CY_SELECT_INPUT";
export const CY_SELECT_INPUT_OPTION = "CY_SELECT_INPUT_OPTION";
