version: "3.9"

services:

  api:
    image: web-api-v2
    build: .
    depends_on:
      - recipe-book-db
    ports:
      - 8080:8080
    working_dir: /web-api-v2
    environment:
      RB__listen_addr: 0.0.0.0:8080
      RB__database_url: postgres://postgres:password@recipe-book-db

  recipe-book-db:
    image: postgres:14
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: password
    volumes:
      - $HOME/dev/personal/recipe-book/recipe-book-app/postgres:/var/lib/postgresql/data

  recipe-book-db-admin:
    image: dpage/pgadmin4:latest
    depends_on:
      - recipe-book-db
    ports:
      - 5050:5050
    environment:
      - PGADMIN_DEFAULT_EMAIL=user@domain.local
      - PGADMIN_DEFAULT_PASSWORD=password
      - PGADMIN_LISTEN_PORT=5050
    volumes:
      - $HOME/dev/personal/recipe-book/recipe-book-app/postgres-admin:/var/lib/pgadmin
    links:
      - recipe-book-db:pgsql-server
