root: true
parser: "@typescript-eslint/parser"
plugins:
    - "@typescript-eslint"
    - "simple-import-sort"

extends:
    - "eslint:recommended"
    - "plugin:@typescript-eslint/recommended"

ignorePatterns:
    # don't ever lint node_modules
    - "node_modules"
    # don't lint build output (make sure it's set to your correct build folder name)
    - "out"

env:
    node: true

rules:
    max-len:
        - warn
        - code: 160
    no-cond-assign: warn
    no-multiple-empty-lines:
        - error
        - max: 3
    semi: "off"
    comma-dangle: "off"
    quotes:
        - error
        - "double"
    no-console: error
    interface-name: "off"
    one-line: "off"
    member-ordering: "off"
    object-literal-sort-keys: "off"
    eol-last:
        - error
        - "always"
    no-shadow: "off"
    object-curly-spacing:
        - warn
        - "always"
    array-bracket-spacing:
        - warn
        - "always"

    simple-import-sort/imports:
        - 2
        - groups:
            -   # Packages. `react` related packages come first.
                - "^react"
                - "^redux"
                - "^next"
                - "^@?\\w"
            -   # Internal packages.
                - "^@common"
                - "^@api"
                - "^@server"
                - "^@client"
            -   # Parent imports. Put `..` last.
                - "^\\.\\.(?!/?$)"
                - "^\\.\\./?$"
            -   # Other relative imports. Put same-folder imports and `.` last.
                - "^\\./(?=.*/)(?!/?$)"
                - "^\\.(?!/?$)"
                - "^\\./?$"
            -   # Style imports.
                - "^.+\\.s?css$"

    "@typescript-eslint/explicit-member-accessibility": error
    "@typescript-eslint/explicit-function-return-type":
        - error
        - allowExpressions: true
    "@typescript-eslint/no-inferrable-types": "off"
    "@typescript-eslint/no-magic-numbers":
        - error
        - ignoreReadonlyClassProperties: true
          ignoreEnums: true
    "@typescript-eslint/array-type":
        - error
        - array: true
    "@typescript-eslint/semi":
        - error
    "@typescript-eslint/comma-dangle":
        - error
        -   # General rule for everything doesn't work with functions
            enums: "always-multiline"
            generics: "always-multiline"
            tuples: "always-multiline"
            arrays: "always-multiline"
            objects: "always-multiline"
            imports: "always-multiline"
            exports: "always-multiline"
            functions: "always-multiline"
    "@typescript-eslint/member-delimiter-style":
        - error
        - singleline:
            delimiter: "comma"
            requireLast: false
    "@typescript-eslint/no-shadow":
        - warn
        - ignoreTypeValueShadow: true
    "@typescript-eslint/consistent-type-imports":
        - warn
        - prefer: type-imports
