extends:
    - stylelint-config-standard-scss
    - stylelint-config-recess-order
rules:
    indentation: 4
    max-empty-lines: 2
    declaration-empty-line-before: null
    no-descending-specificity: null
    no-empty-first-line: null
    at-rule-empty-line-before: null
    at-rule-no-unknown:
        - true
        - ignoreAtRules:
            - mixin
            - include
    selector-class-pattern: null
    color-function-notation: legacy
    alpha-value-notation: number
    scss/dollar-variable-empty-line-before: null
    scss/at-import-partial-extension: always
