name: auth-api

on:
    push:
        branches:
            - main
            - develop
            - feature/*
            - fix/*
        paths:
            - services/auth-api/**
            - .github/workflows/auth-api.yml

    # Allows you to run this workflow manually from the Actions tab
    workflow_dispatch:

# NOTE: Can't run keycloak container (and as a result integration tests) for testing because GH Actions don't support command specification 

jobs:

    lint:
        runs-on: ubuntu-20.04

        steps:
            - uses: actions/checkout@v3

            - name: Install stable toolchain
              uses: actions-rs/toolchain@v1
              with:
                  profile: minimal
                  toolchain: stable
                  override: true
                  components: rustfmt, clippy

            - name: Run cargo check
              uses: actions-rs/cargo@v1
              with:
                  command: check
                  args: --manifest-path services/auth-api/Cargo.toml

            - name: Run cargo fmt
              uses: actions-rs/cargo@v1
              with:
                  command: fmt
                  args: --manifest-path services/auth-api/Cargo.toml --all -- --check

            - name: Run cargo clippy
              uses: actions-rs/cargo@v1
              with:
                  command: clippy
                  args: --manifest-path services/auth-api/Cargo.toml -- -D warnings
