name: CI

on:
    push:
        branches: [ main ]
    pull_request:
        branches: [ main ]

    # Allows you to run this workflow manually from the Actions tab
    workflow_dispatch:

jobs:

    build-web-app:
        runs-on: ubuntu-20.04

        defaults:
            run:
                working-directory: services/web-app

        strategy:
            matrix:
                node-version: [ 16.x ]

        steps:
            - uses: actions/checkout@v2
            
            - name: use node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v1
              with:
                node-version: ${{ matrix.node-version }}

            - run: npm install
            - run: npm run build

    lint-web-app:
        runs-on: ubuntu-20.04

        defaults:
            run:
                working-directory: services/web-app

        strategy:
            matrix:
                node-version: [ 16.x ]

        steps:
            - uses: actions/checkout@v2
            
            - name: use node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v1
              with:
                node-version: ${{ matrix.node-version }}

            - run: npm install
            - run: npm run lint

    test-web-app:
        runs-on: ubuntu-20.04

        defaults:
            run:
                working-directory: services/web-app

        strategy:
            matrix:
                node-version: [ 16.x ]

        steps:
            - uses: actions/checkout@v2
            
            - name: use node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v1
              with:
                node-version: ${{ matrix.node-version }}

            - run: npm install
            - run: npm run test
