name: web-api

on:
    push:
        branches:
            - main
            - develop
        paths:
            - services/web-api/**
            - .github/workflows/web-api.yml
    pull_request:
        branches:
            - main
            - develop
        paths:
            - services/web-api/**
            - .github/workflows/web-api.yml

    # Allows you to run this workflow manually from the Actions tab
    workflow_dispatch:

jobs:

    lint:
        runs-on: ubuntu-20.04

        steps:
            - uses: actions/checkout@v3

            - name: Install stable toolchain
              uses: actions-rs/toolchain@v1
              with:
                  profile: minimal
                  toolchain: stable
                  override: true
                  components: rustfmt, clippy

            - name: Run cargo check
              uses: actions-rs/cargo@v1
              with:
                  command: check
                  args: --manifest-path services/web-api/Cargo.toml

            - name: Run cargo fmt
              uses: actions-rs/cargo@v1
              with:
                  command: fmt
                  args: --manifest-path services/web-api/Cargo.toml --all -- --check

            - name: Run cargo clippy
              uses: actions-rs/cargo@v1
              with:
                  command: clippy
                  args: --manifest-path services/web-api/Cargo.toml -- -D warnings

    test:
        runs-on: ubuntu-20.04

        services:
            recipe-book-db:
                image: postgres:14
                ports:
                    - 5432:5432
                env:
                    POSTGRES_PASSWORD: password
                options: >-
                    --health-cmd pg_isready
                    --health-interval 10s
                    --health-timeout 5s
                    --health-retries 5

        steps:
            - uses: actions/checkout@v3

            - name: Install stable toolchain
              uses: actions-rs/toolchain@v1
              with:
                  profile: minimal
                  toolchain: stable
                  override: true

            - name: Migrate database
              uses: actions-rs/cargo@v1
              with:
                  command: run
                  args: --manifest-path tools/rba-cli/Cargo.toml -- migrate-database 'postgres://postgres:password@localhost'

            - name: Seed database
              uses: actions-rs/cargo@v1
              with:
                  command: run
                  args: --manifest-path tools/rba-cli/Cargo.toml -- seed-database 'postgres://postgres:password@localhost'

            - name: Run cargo test
              uses: actions-rs/cargo@v1
              with:
                  command: test
                  args: --manifest-path services/web-api/Cargo.toml
