name: web-app

defaults:
    run:
        working-directory: services/web-app

on:
    push:
        branches:
            - main
            - develop
        paths:
            - services/web-app/**
            - .github/workflows/web-app.yml
    pull_request:
        branches:
            - main
            - develop
        paths:
            - services/web-app/**
            - .github/workflows/web-app.yml

    # Allows you to run this workflow manually from the Actions tab
    workflow_dispatch:

jobs:

    build:
        runs-on: ubuntu-20.04

        strategy:
            matrix:
                node-version: [ 16.x ]

        steps:
            - uses: actions/checkout@v2
            
            - name: use node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v1
              with:
                node-version: ${{ matrix.node-version }}

            - run: npm install
            - run: npm run build

    lint:
        runs-on: ubuntu-20.04

        strategy:
            matrix:
                node-version: [ 16.x ]

        steps:
            - uses: actions/checkout@v2
            
            - name: use node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v1
              with:
                node-version: ${{ matrix.node-version }}

            - run: npm install
            - run: npm run lint

    lint-style:
        runs-on: ubuntu-20.04

        strategy:
            matrix:
                node-version: [ 16.x ]

        steps:
            - uses: actions/checkout@v2
            
            - name: use node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v1
              with:
                node-version: ${{ matrix.node-version }}

            - run: npm install
            - run: npm run lint:style

    test:
        runs-on: ubuntu-20.04

        strategy:
            matrix:
                node-version: [ 16.x ]

        steps:
            - uses: actions/checkout@v2
            
            - name: use node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v1
              with:
                node-version: ${{ matrix.node-version }}

            - name: run cypress tests in chrome
              uses: cypress-io/github-action@v2
              with:
                working-directory: services/web-app
                browser: chrome
                build: npm run build
                start: npm start
